apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudservice
    spec:
      containers:
        - image: gcr.io/christian-blake/cloudservice:v1
          name: web
          env:
            - name: DB_HOST
              value: 127.0.0.1:3306
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
          ports:
            - containerPort: 8080
              name: cloudcluster
        - image: gcr.io/cloudsql-docker/gce-proxy:1.09
          name: cloudsql-proxy
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=christian-blake:us-central1:christian-blake-10=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
      # [END volumes]